### ISSUE TITLE
Franklin.jl でサイトを作る

### ISSUE THREAD

**Issue by mrkn** [JuliaLangJa/operations#3]

**Comment by hyrodium** [comment]
サイトには下記項目以外に何か必要でしょうか?

* 最低限必要
  * Discordへの招待リンク
  * 行動規範
* あった方が良いかも
  * Julia言語入門
    * Julia言語を初めて触る人を想定した入門資料があると嬉しい
    * インストールにはjuliaupを使う
    * REPLの簡単な紹介
    * Pluto.jlの紹介
  * お役立ちリンク集
    * 日本語書籍情報
    * Julia関連サイト

[NumPy](https://numpy.org/ja/)の日本語ページは参考になりそうです。
[ruby-jp](https://ruby-jp.github.io/)はSlackの招待リンクと行動規範のみでシンプルなようですね。

**Comment by hyrodium** [comment]
どのテンプレートを使うかも検討したいですね。

https://github.com/tlienart/FranklinTemplates.jl

**Comment by mrkn** [comment]
シンプルな入口ページだけ先に素早く用意したいなと考えてました。その内容は ruby-jp の様な感じで次のものがあれば十分だと思います。

* Discord への招待リンク
* 行動規範
* ruby-jp のページにある次の内容を JuliaLangJa 向けに書き換えたもの
    * JuliaLangJa の使い方
    * Julia 入門者・学生の方へ
    * 自己紹介をしましょう

ruby-jp は Ruby のコンテキストを暗黙の前提に書いている部分がいくつかあります。そのコンテキストを想像してみると、以下の様なことが暗黙的に想定されているはずです。

* 利用者の大半が企業のプログラマーであること
* 多くの企業が Ruby on Rails のために Ruby を使っていること
* Ruby エンジニア向けの求人が多いこと
* プログラミングスクールで Ruby を学んでいる人が多いこと
* 学生の Rubyist はパイが小さく貴重であること

そのため、ruby-jp のページに書いてある内容をそのまま持ってきて機械的に名詞を置き換えるだけでは不適切な内容になってしまうので、使い方などの内容も JuliaLangJa 向けに作りなおしたいです。

「Julia に興味を持ち始めた人が軽い気持ちで参加して安心して質問をしたり交流したりできる場である」ことが伝わる雰囲気のトップページになればいいなと考えています。

**Comment by mrkn** [comment]
テンプレートは迷いますね！プレビューをいくつか見てみて、少なくともトップページはリファレンスマニュアルっぽくないやつがいいんだろうな、ということだけ思いました。

**Comment by hyrodium** [comment]
GitHub organizationにdiscord招待リンクを記載しました。Franklinのページが作成されるまでは暫定的にこのページをコミュニティのトップページとして良いかと思います。

https://github.com/JuliaLangJa

**Comment by mrkn** [comment]
ありがとうございます！

**Comment by mrkn** [comment]
ウェブサイトの叩き台を作りました。
https://github.com/JuliaLangJa/julialangja.github.io

* 叩き台なので深く考えず basic テンプレートを選択した
* 最低限のレスポンシブ対応のみ
* favicon の置き換え

だけやってます。どんどん更新しちゃってください！

いま上がってそうなサイト関係の issue を https://github.com/JuliaLangJa/julialangja.github.io/issues に作りました。

**Comment by hyrodium** [comment]
サイト自体は用意してもらったので、今後はそちらのissueで議論しましょう！
