### ISSUE TITLE
JuliaLangJaのロゴの作成

### ISSUE THREAD

**Issue by hyrodium** [JuliaLangJa/operations#4]
以下の用途を検討しています。

* Discord
* JuliaLangJaのGitHub organization
* サイトトップページ

https://publicdomainq.net/japanese-map-0006480/ の画像を少し編集しただけですが、以下の画像のように日本地図をjulia-logo-colorsで4色に塗り分けたものを考えています。

![image](https://github.com/JuliaLangJa/operations/assets/7488140/fac9ebf0-8245-4d85-a3ee-19e8e1bcf8f9)

形状はもっとブラッシュアップする予定ですが、このような方針でいかがでしょうか？

**Comment by mrkn** [comment]
とても良いと思いました！

**Comment by hyrodium** [comment]
![image](https://github.com/JuliaLangJa/operations/assets/7488140/b68fdddd-6ba2-483f-8035-19986aaba48a)

円板と正方形に合わせてアイコンを微調整してみました。

@mrkn @antimon2 何かご意見あればお願いします！

**Comment by mrkn** [comment]
余白のバランスの関係なのか、それともロゴが四角で構成されているからなのか、四角い方がなんかすっきりしますね

**Comment by hyrodium** [comment]
確かにそれは少し懸念していました。GitHub organizationが四角でDiscordが丸なので、Discordで見栄えが良いかが気掛かりです。

違和感などあった場合に修正することを前提に、試しに設定してみても良いでしょうか？

**Comment by antimon2** [comment]
> 違和感などあった場合に修正することを前提に、試しに設定してみても良いでしょうか？

良いです！お試しください！

**Comment by hyrodium** [comment]
とりあえず

* GitHub organization
* Discord

に透過背景で設定しました。
ロゴ管理リポジトリ→https://github.com/JuliaLangJa/JuliaLangJaLogo

---

Discordは厳密には丸アイコンだけでは無かったですね。

![Peek 2024-03-12 12-38](https://github.com/JuliaLangJa/operations/assets/7488140/f84a46c2-ab6e-4d0b-8658-8427d665ab4f)

**Comment by hyrodium** [comment]
他のロゴ案:

![image](https://github.com/JuliaLangJa/operations/assets/7488140/dcfda91c-ec36-402d-a947-feb01b60f382)

**Comment by mrkn** [comment]
@hyrodium ウェブサイトの方に掲示するロゴは最初に作ってくださった斜めのやつが良いかもしれないなと思って、一旦それを配置しています。もし斜めになってないロゴで統一したければ取り替えても良いと思いますが、どうでしょうか？

**Comment by hyrodium** [comment]
>もし斜めになってないロゴで統一したければ取り替えても良いと思いますが、どうでしょうか？

たしかに、配置スペース的には斜めの方が収まりが良さそうですね。冒頭のロゴはあくまで草案だったので

* 正方形ロゴを変形させて配置
* ロゴの横に「Julia日本語コミュニティ」の文字列を配置

などの修正が良さそうに感じています。時間のあるときにPR作成してみます！

**Comment by antimon2** [comment]
今さらかも知れませんが、今朝になって見直して思いついたことをちょっと書いてみます。
このロゴ、Julia色は使ってるんですがそれ以外のJuliaっぽさがないなーと思ってたのですがその違和感？の理由が分かったような気がするので。

+ ●っぽさがどこかにあるともう少しJuliaっぽさが出るのでは？（北海道か九州を●にしちゃうとか全体的に角R値を大きめににするとか）
    + Julia本家のロゴ（∴ 型のシンプル版）は「3色」∪「3つの●」でブランディングしているような気がする、提案のロゴは色情報が欠落すると「日本地図を図案化したもの」にしか見えなくなる
    + 参考：JuliaTokaiのロゴは色情報欠落しても「あの吹き出しみたいな顔みたいなカタチが4つ」で一応訴求しているつもり
+ https://github.com/JuliaLangJa/operations/issues/4#issuecomment-1990125007 の他のロゴ案のように、Julia 指定のフォントを使った文字が何かはいっていることで「Julia の」感が出せそう
    + JuliaTokai の文字入りロゴはあのフォント使ってる

ボツ案：

+ 北海道と本州で「j」を作る（…とか考えたんですが絶対まとまらなくなりそうなので取り下げますw）

**Comment by hyrodium** [comment]
諸々ご意見感謝です！

>提案のロゴは色情報が欠落すると「日本地図を図案化したもの」にしか見えなくなる

仰る通りで、全くイケてないので修正したいですね…！

>北海道か九州を●にしちゃうとか全体的に角R値を大きめににするとか

バリエーション幾つか作成してみます。

>参考：JuliaTokaiのロゴは色情報欠落しても「あの吹き出しみたいな顔みたいなカタチが4つ」で一応訴求しているつもり

JuliaTokaiロゴは私も気に入っているので、JuliaTokaiのロゴをJuliaLangJaのロゴと共通化することも可能性としてあるかも、とは思っています。

>ボツ案

他にも○感を出すために日本地図をFourier級数で近似して高周波項打ち切りするのも良いかと思っていましたが、ロゴにするには本州が大きすぎて諦めたりもしましたw

**Comment by hyrodium** [comment]
とりあえずロゴの作成までは完了したのでcloseします。詳細な検討は新しいリポジトリの方で検討しましょう。
